In [1]:
import torch
print(torch.__version__)

2.9.1+cpu


In [2]:
if torch.cuda.is_available():
  print("Gpu is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU not available. Using CPU


## Creating Tensors

In [3]:
# using empty
a = torch.empty(2,3)

In [4]:
type(a) # check type

torch.Tensor

In [5]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2,3)

tensor([[0.3366, 0.7958, 0.5681],
        [0.1513, 0.5332, 0.6466]])

In [8]:
# use of seed (for the same value in rand)
torch.rand(2,3)

tensor([[0.7074, 0.5629, 0.9320],
        [0.3058, 0.1472, 0.2316]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]]) # custom tensors

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
# other ways

# arange
print('using arange ->', torch.arange(0,10,2))

# using linspace
print('using linspace ->', torch.linspace(0,10,10)) # evenly spaced values

# using eye
print('using eye ->', torch.eye(5)) # identity matrix

# using full
print('using full ->', torch.full((3,3), 5)) # shape 3x3 every item is 5

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [12]:
x = torch.tensor([[2,2,2],[3,3,3]])
x

tensor([[2, 2, 2],
        [3, 3, 3]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x) # another variable like x

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [17]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [18]:
# find data types
x.dtype

torch.int64

In [19]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [21]:
# using to()
x.to(torch.float32)

tensor([[2., 2., 2.],
        [3., 3., 3.]])

## Mathematical Operations

### 1. Scalar operation

In [22]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [23]:
# addition
x + 2
# substraction
x-2
# multiplication
x * 3
# division
x / 3
# int division
(x *100) // 3
# mod
((x *100) // 3) % 2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [24]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [25]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a**b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [26]:
c = torch.tensor([1,-2,3,-4])

In [27]:
# abs for absolute value
torch.abs(c)

tensor([1, 2, 3, 4])

In [28]:
# negative
torch.neg(c) # 1 = -1, -2 = 2 etc

tensor([-1,  2, -3,  4])

In [29]:
# round
d = torch.tensor([1.9,2.3,3.7,4.4])

torch.round(d)

tensor([2., 2., 4., 4.])

In [30]:
# ceil

torch.ceil(d)

tensor([2., 3., 4., 5.])

In [31]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [32]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [33]:
e = torch.randint(size=(2,3),low=0, high=10, dtype=torch.float32)
e # whole tensor in one digit using reduction operations

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [34]:
# sum (sum the whole tensor)
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([15.,  9.])

In [35]:
# mean
torch.mean(e) # only works when dtype is float
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [36]:
# median
torch.median(e)

tensor(0.)

In [37]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [38]:
# product
torch.prod(e)

tensor(0.)

In [39]:
# standard deviation
torch.std(e)

tensor(4.4272)

In [40]:
# variance
torch.var(e)

tensor(19.6000)

In [41]:
# argmax
torch.argmax(e) # position of the biggest argument

tensor(5)

In [42]:
# argmin
torch.argmin(e) # position of the smallest argument in the tensor

tensor(1)

### 4. Matrix Operation

In [43]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [44]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [45]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [46]:
# transpose
torch.transpose(f, 0, 1) # 0 to 1

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [47]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [48]:
# dererminant
torch.det(h)

tensor(-110.0000)

In [49]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

### 5. Comparision Operations

In [50]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [51]:
# greater than
i > j
# less than
i < j
# equal to
i==j
# greater than equals to
i>=j
# less than equals to
i<=j

tensor([[False, False,  True],
        [False,  True,  True]])

### 6. Special functions

In [52]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [53]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [54]:
# exponents
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [55]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [56]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [57]:
# softmax
torch.softmax(k,dim=0) # tensor must be float

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [58]:
# relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

## Inplace Operations

In [59]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [60]:
m + n # a new tensor will form and occupy the memory *problem

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [61]:
m.add_(n) # for inplace

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [62]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [63]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [64]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [65]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

## Copying a tensor

In [66]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [67]:
b = a
b # *problem: if any changes in a it also changes

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [68]:
b = a.clone() # solution

## Tensor Operations on GPU

In [69]:
torch.cuda.is_available()

False

In [70]:
device = torch.device('cuda')

In [71]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
# moving an existing tensor on GPU
a = torch.rand(2,3)
a

In [ ]:
b = a.to(device)
b

In [ ]:
# 10k x 10k shape metrics cpu vs gpu, cpu took 17 sec and gpu took 0.54

## Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten (single dimension)
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.9112, 0.4847, 0.9436, 0.3904],
         [0.2499, 0.3206, 0.9753, 0.7582],
         [0.6688, 0.2651, 0.2336, 0.5057]],

        [[0.5688, 0.0634, 0.8993, 0.2732],
         [0.3397, 0.1879, 0.5534, 0.2682],
         [0.9556, 0.9761, 0.5934, 0.3124]]])

In [ ]:
# permute
b.permute(2,0,1) # 2 index 0 will be on 2nd position,  1 index '3' will be on last etc
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze (adding dimension)
# image size (226,226,3)

c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy and PyTorch

In [ ]:
import torch
import numpy as np
# converting numpy arrays to pytorch tensors and vice versa

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy() # converted to numpy array from tensor
b

array([1, 2, 3])

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
d = torch.from_numpy(c) # converted to tensor
d

tensor([1, 2, 3])